on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to check prime
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: prime action step
        uses: ./ # Uses an action in the root directory
        id: hello
 